// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifneebjrtpoqugrmcsax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmbmVlYmpydHBvcXVncm1jc2F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwMTM5NTIsImV4cCI6MjA4NjU4OTk1Mn0.JubCBNic5dplRJCo3PZ-5W9OVrzexf-j4vzuud1mopc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});